set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(CMAKE_SYSROOT "")
set(HAVE_FLAG_SEARCH_PATHS_FIRST 0)

set(BREW_LLVM_PATH /opt/homebrew/opt/llvm)
set(CMAKE_C_COMPILER ${BREW_LLVM_PATH}/bin/clang)
set(CMAKE_CXX_COMPILER ${BREW_LLVM_PATH}/bin/clang++)
set(CMAKE_LINKER ${BREW_LLVM_PATH}/bin/ld.lld)

#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
